slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: true
    map_file_name: "map"
    mode: "mapping"
    map_start_pose: [0.0, 0.0, 0.0]
    resolution: 0.05
    max_laser_range: 15.0
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    transform_publish_period: 0.05
    map_update_interval: 5.0
    map_topic: "/map"
    scan_topic: "/scan"  # Remap to /scan
    base_frame: "laser"  # Change to your robot's base frame
    odom_frame: "odom"
    map_frame: "map"
    max_submaps: 30
    minimum_time_interval: 0.0
    max_optimizations: 100

    # Optimization parameters
    max_laser_range: 15.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.17
    transform_publish_period: 0.05
    map_update_interval: 3.0

    # Scan matching parameters
    loop_closure_threshold: 0.11
    max_tolerable_fitness_score: 0.5

    # Solver parameters
    use_pose_graph: true
    use_scan_barycenter: false
    solver_type: "ceres"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "JACOBI"

    # Map parameters
    map_resolution: 0.05
    max_lidar_range: 15.0

    # Output directory
    output_directory: "~/.ros/slam_toolbox"

    # TF settings
    use_scan_matching: true
    transform_tolerance: 0.2
    scan_match_tolerance: 0.01
    max_interpolation_dist: 1.0
    interpolate_scan: true
    scan_match_min_score: 0.8

